// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using AU.Infrastructure.Persistence;

#nullable disable

namespace AU.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260923222313_TimescaleChecks")]
    partial class TimescaleChecks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AU.Application.Checks.ReadModels.MonitorCheckDaily", b =>
                {
                    b.Property<DateTimeOffset>("Bucket")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaxResponseTimeMs")
                        .HasColumnType("integer");

                    b.Property<int?>("MinResponseTimeMs")
                        .HasColumnType("integer");

                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid");

                    b.Property<long>("ResponseTimeCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("ResponseTimeSumMs")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalChecks")
                        .HasColumnType("bigint");

                    b.Property<long>("UpChecks")
                        .HasColumnType("bigint");

                    b.ToTable((string)null);

                    b.ToView("monitor_checks_daily", (string)null);

                    b
                        .HasAnnotation("TimescaleDb:ContinuousAggregate:MaterializedOnly", false)
                        .HasAnnotation("TimescaleDb:ContinuousAggregate:Query", "SELECT time_bucket(INTERVAL '1 day', h.\"Bucket\") AS \"Bucket\",\n       h.\"MonitorId\",\n       sum(h.\"TotalChecks\")::bigint AS \"TotalChecks\",\n       sum(h.\"UpChecks\")::bigint AS \"UpChecks\",\n       sum(h.\"ResponseTimeCount\")::bigint AS \"ResponseTimeCount\",\n       sum(h.\"ResponseTimeSumMs\")::bigint AS \"ResponseTimeSumMs\",\n       min(h.\"MinResponseTimeMs\") AS \"MinResponseTimeMs\",\n       max(h.\"MaxResponseTimeMs\") AS \"MaxResponseTimeMs\"\nFROM monitor_checks_hourly AS h\nGROUP BY 1, 2")
                        .HasAnnotation("TimescaleDb:ContinuousAggregate:WithNoData", true)
                        .HasAnnotation("TimescaleDb:IsContinuousAggregate", true)
                        .HasAnnotation("TimescaleDb:RefreshPolicy:EndOffset", "01:00:00")
                        .HasAnnotation("TimescaleDb:RefreshPolicy:ScheduleInterval", "01:00:00")
                        .HasAnnotation("TimescaleDb:RefreshPolicy:StartOffset", "3 days");
                });

            modelBuilder.Entity("AU.Application.Checks.ReadModels.MonitorCheckHourly", b =>
                {
                    b.Property<DateTimeOffset>("Bucket")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaxResponseTimeMs")
                        .HasColumnType("integer");

                    b.Property<int?>("MinResponseTimeMs")
                        .HasColumnType("integer");

                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid");

                    b.Property<long>("ResponseTimeCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("ResponseTimeSumMs")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalChecks")
                        .HasColumnType("bigint");

                    b.Property<long>("UpChecks")
                        .HasColumnType("bigint");

                    b.ToTable((string)null);

                    b.ToView("monitor_checks_hourly", (string)null);

                    b
                        .HasAnnotation("TimescaleDb:ContinuousAggregate:MaterializedOnly", false)
                        .HasAnnotation("TimescaleDb:ContinuousAggregate:Query", "SELECT time_bucket(INTERVAL '1 hour', c.checked_at) AS \"Bucket\",\n       c.monitor_id AS \"MonitorId\",\n       count(*) AS \"TotalChecks\",\n       count(*) FILTER (WHERE c.status = 'UP') AS \"UpChecks\",\n       count(c.response_time_ms) AS \"ResponseTimeCount\",\n       sum(c.response_time_ms) AS \"ResponseTimeSumMs\",\n       min(c.response_time_ms) AS \"MinResponseTimeMs\",\n       max(c.response_time_ms) AS \"MaxResponseTimeMs\"\nFROM checks AS c\nGROUP BY 1, 2")
                        .HasAnnotation("TimescaleDb:ContinuousAggregate:WithNoData", true)
                        .HasAnnotation("TimescaleDb:IsContinuousAggregate", true)
                        .HasAnnotation("TimescaleDb:RefreshPolicy:EndOffset", "01:00:00")
                        .HasAnnotation("TimescaleDb:RefreshPolicy:ScheduleInterval", "00:30:00")
                        .HasAnnotation("TimescaleDb:RefreshPolicy:StartOffset", "3 days")
                        .HasAnnotation("TimescaleDb:RetentionPolicy:DropAfter", "2 years");
                });

            modelBuilder.Entity("AU.Domain.Entities.Check", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("monitor_id");

                    b.Property<int?>("ResponseTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("response_time_ms");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.HasKey("Id", "CheckedAt");

                    b.HasIndex("MonitorId", "CheckedAt");

                    b.ToTable("checks", (string)null);

                    b
                        .HasAnnotation("TimescaleDb:Columnstore:Enabled", true)
                        .HasAnnotation("TimescaleDb:Columnstore:OrderBy", "checked_at DESC")
                        .HasAnnotation("TimescaleDb:Columnstore:SegmentBy", "monitor_id")
                        .HasAnnotation("TimescaleDb:ColumnstorePolicy:After", "1 day")
                        .HasAnnotation("TimescaleDb:Hypertable:ChunkInterval", "1 day")
                        .HasAnnotation("TimescaleDb:Hypertable:PartitionColumn", "checked_at")
                        .HasAnnotation("TimescaleDb:IsHypertable", true)
                        .HasAnnotation("TimescaleDb:RetentionPolicy:DropAfter", "30 days");
                });

            modelBuilder.Entity("AU.Domain.Entities.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedChecksCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MonitorId", "Status");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("AU.Domain.Entities.IncidentNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.ToTable("incidents_notifications", (string)null);
                });

            modelBuilder.Entity("AU.Domain.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "Email")
                        .IsUnique()
                        .HasFilter("\"AcceptedAt\" IS NULL AND \"RevokedAt\" IS NULL");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("AU.Domain.Entities.Monitor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AlertThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<string>("Config")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("IntervalSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("NotifyOnRecovery")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("RecoveryThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TimeoutMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5000);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("OrganizationId");

                    b.ToTable("monitors", (string)null);
                });

            modelBuilder.Entity("AU.Domain.Entities.MonitorNotificationChannel", b =>
                {
                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NotificationChannelId")
                        .HasColumnType("uuid");

                    b.HasKey("MonitorId", "NotificationChannelId");

                    b.HasIndex("NotificationChannelId");

                    b.ToTable("monitor_notification_channels", (string)null);
                });

            modelBuilder.Entity("AU.Domain.Entities.MonitorState", b =>
                {
                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid");

                    b.Property<int>("ConsecutiveFailures")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("ConsecutiveSuccesses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("NextCheckAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("MonitorId");

                    b.HasIndex("NextCheckAt");

                    b.ToTable("monitor_states", (string)null);
                });

            modelBuilder.Entity("AU.Domain.Entities.NotificationChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("notification_channels", (string)null);
                });

            modelBuilder.Entity("AU.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("AU.Domain.Entities.OrganizationMember", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("OrganizationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("OrganizationMembers");
                });

            modelBuilder.Entity("AU.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("AU.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("AU.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("AU.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AU.Domain.Entities.Check", b =>
                {
                    b.HasOne("AU.Domain.Entities.Monitor", null)
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AU.Domain.Entities.Incident", b =>
                {
                    b.HasOne("AU.Domain.Entities.Monitor", null)
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AU.Domain.Entities.IncidentNotification", b =>
                {
                    b.HasOne("AU.Domain.Entities.Incident", null)
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AU.Domain.Entities.Invitation", b =>
                {
                    b.HasOne("AU.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("AU.Domain.Entities.Monitor", b =>
                {
                    b.HasOne("AU.Domain.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AU.Domain.Entities.MonitorNotificationChannel", b =>
                {
                    b.HasOne("AU.Domain.Entities.Monitor", null)
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AU.Domain.Entities.NotificationChannel", null)
                        .WithMany()
                        .HasForeignKey("NotificationChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AU.Domain.Entities.MonitorState", b =>
                {
                    b.HasOne("AU.Domain.Entities.Monitor", null)
                        .WithOne("State")
                        .HasForeignKey("AU.Domain.Entities.MonitorState", "MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AU.Domain.Entities.NotificationChannel", b =>
                {
                    b.HasOne("AU.Domain.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AU.Domain.Entities.OrganizationMember", b =>
                {
                    b.HasOne("AU.Domain.Entities.Organization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AU.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("AU.Domain.Entities.Monitor", b =>
                {
                    b.Navigation("State")
                        .IsRequired();
                });

            modelBuilder.Entity("AU.Domain.Entities.Organization", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
