<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-US.CheckWorker-fa97abeb-093a-494e-9a66-80cf38b54c9a</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.5.4" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
        <PackageReference Include="WolverineFx" Version="6.40.0" />
        <PackageReference Include="WolverineFx.RabbitMQ" Version="6.40.0" />
        <PackageReference Include="WolverineFx.RuntimeCompilation" Version="6.40.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\US.Application\US.Application.csproj" />
      <ProjectReference Include="..\US.Infrastructure\US.Infrastructure.csproj" />
    </ItemGroup>
</Project>
