<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-US.CheckScheduler-66f7288d-6c0f-437f-9821-82cafa47c9f6</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.5.4" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
        <PackageReference Include="WolverineFx.RabbitMQ" Version="6.40.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AU.Api\AU.Api.csproj" />
      <ProjectReference Include="..\AU.Infrastructure\AU.Infrastructure.csproj" />
    </ItemGroup>
</Project>
