apiVersion: 1

contactPoints:
  - orgId: 1
    name: email
    receivers:
      - uid: email-alerts
        type: email
        settings:
          addresses: ${ALERT_EMAIL}
          singleEmail: true
        disableResolveMessage: false

policies:
  - orgId: 1
    receiver: email
    group_by:
      - grafana_folder
      - alertname
      - server
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
